import {
  Wallet,
  TrendingUp,
  TrendingDown,
  CreditCard,
  ShoppingBag,
  ShoppingCart,
  Package,
  Bell,
  PieChart,
  Settings,
  LogOut,
  Plus,
  RefreshCw,
  ArrowUpRight,
  Info,
  Lightbulb,
  Target,
  AlertCircle,
  PiggyBank,
  BarChart3,
  DollarSign,
  Receipt,
  Shield,
  Clock,
  TrendingUp as TrendingUpIcon,
  Wallet as WalletIcon,
  CreditCard as CreditCardIcon,
  Calculator,
  Landmark,
  Coins,
  Percent,
  AlertTriangle,
  CheckCircle,
  Sparkles,
  Gift,
  Heart,
  Star,
  Trophy,
  Zap,
  Flame,
  Moon,
  Sun,
  Cloud,
  Droplet,
  Flower,
  Trees,
  Home,
  Car,
  Bike,
  Bus,
  Plane,
  Train,
  Ship,
  Coffee,
  Beer,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Camera,
  Music,
  Film,
  Gamepad,
  Book,
  Pen,
  Briefcase,
  Medal,
  Award,
  FileText,
  Download,
  Calendar,
  Target as TargetIcon,
  ArrowRight,
  ArrowUpCircle,
  ArrowDownCircle,
} from "lucide-react";

export const financialTips = [
  {
    icon: PiggyBank,
    title: "Reserva",
    content: "Mantenha 3-6 meses de despesas em reserva",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
  },
  {
    icon: Target,
    title: "Regra 50-30-20",
    content: "50% necessidades, 30% desejos, 20% economia",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: AlertCircle,
    title: "Dívidas",
    content: "Pague o cartão integralmente todo mês",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: Lightbulb,
    title: "Automação",
    content: "Automatize transferências para investimentos",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: BarChart3,
    title: "Acompanhe",
    content: "Revise suas finanças semanalmente",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: DollarSign,
    title: "Renda Extra",
    content: "Busque fontes adicionais de renda",
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  {
    icon: Receipt,
    title: "Controle",
    content: "Anote todos os gastos, mesmo pequenos",
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    icon: Shield,
    title: "Seguros",
    content: "Proteja seu patrimônio com seguros",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: Clock,
    title: "Juros",
    content: "Comece cedo para aproveitar juros compostos",
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
  },
  {
    icon: TrendingUpIcon,
    title: "Invista",
    content: "Diversifique para reduzir riscos",
    color: "text-lime-400",
    bgColor: "bg-lime-500/10",
  },
  {
    icon: WalletIcon,
    title: "Orçamento",
    content: "Planeje gastos antes do mês começar",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
  },
  {
    icon: CreditCardIcon,
    title: "Cartão",
    content: "Use no máximo 30% do limite",
    color: "text-rose-400",
    bgColor: "bg-rose-500/10",
  },
  {
    icon: Calculator,
    title: "Financiamento",
    content: "Calcule juros antes de financiar",
    color: "text-violet-400",
    bgColor: "bg-violet-500/10",
  },
  {
    icon: Landmark,
    title: "Impostos",
    content: "Separe dinheiro para impostos anuais",
    color: "text-teal-400",
    bgColor: "bg-teal-500/10",
  },
  {
    icon: Coins,
    title: "Moeda Forte",
    content: "Considere investir em dólar/euro",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Percent,
    title: "Taxas",
    content: "Evite taxas com contas digitais",
    color: "text-sky-400",
    bgColor: "bg-sky-500/10",
  },
  {
    icon: AlertTriangle,
    title: "Golpes",
    content: "Desconfie de ganhos fáceis",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: CheckCircle,
    title: "Metas",
    content: "Defina metas específicas",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
  },
  {
    icon: Sparkles,
    title: "Educação",
    content: "Invista em conhecimento financeiro",
    color: "text-fuchsia-400",
    bgColor: "bg-fuchsia-500/10",
  },
  {
    icon: PiggyBank,
    title: "Cofrinho",
    content: "Guarde moedas digitalmente",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Target,
    title: "Priorize",
    content: "Pague dívidas com juros altos primeiro",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Lightbulb,
    title: "Despesas Fixas",
    content: "Mantenha abaixo de 50% da renda",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: BarChart3,
    title: "Pesquise",
    content: "Sempre compare preços",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: DollarSign,
    title: "Aposentadoria",
    content: "Planeje sua aposentadoria agora",
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  {
    icon: Receipt,
    title: "Notas",
    content: "Guarde notas fiscais importantes",
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    icon: Shield,
    title: "Dados",
    content: "Proteja informações bancárias",
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
  },
  {
    icon: Clock,
    title: "Prazos",
    content: "Pague contas antes do vencimento",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
  },
  {
    icon: TrendingUpIcon,
    title: "Renda",
    content: "Busque aumentos/promoções",
    color: "text-lime-400",
    bgColor: "bg-lime-500/10",
  },
  {
    icon: WalletIcon,
    title: "Cartões",
    content: "Tenha controle de todos",
    color: "text-rose-400",
    bgColor: "bg-rose-500/10",
  },
  {
    icon: CreditCardIcon,
    title: "Cashback",
    content: "Use cartões com cashback",
    color: "text-violet-400",
    bgColor: "bg-violet-500/10",
  },
  {
    icon: Calculator,
    title: "Custo de Vida",
    content: "Calcule seu custo exato",
    color: "text-teal-400",
    bgColor: "bg-teal-500/10",
  },
  {
    icon: Landmark,
    title: "Banco Digital",
    content: "Use bancos sem taxas",
    color: "text-sky-400",
    bgColor: "bg-sky-500/10",
  },
  {
    icon: Coins,
    title: "Invista",
    content: "Comece mesmo com pouco",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Percent,
    title: "CDI vs Selic",
    content: "Entenda a diferença",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
  },
  {
    icon: AlertTriangle,
    title: "Cheque Especial",
    content: "Evite (juros altos)",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: CheckCircle,
    title: "Revisão",
    content: "Revista investimentos anualmente",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Sparkles,
    title: "Liberdade",
    content: "Trabalhe pela liberdade financeira",
    color: "text-fuchsia-400",
    bgColor: "bg-fuchsia-500/10",
  },
  {
    icon: PiggyBank,
    title: "Economia",
    content: "Economize em contas (luz/água)",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Target,
    title: "Emergência",
    content: "Tenha fundo para imprevistos",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: Lightbulb,
    title: "Consumo",
    content: "Pense: preciso mesmo?",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: Gift,
    title: "Presentes",
    content: "Planeje gastos com presentes antecipadamente",
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    icon: Heart,
    title: "Saúde",
    content: "Invista em prevenção e plano de saúde",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: Star,
    title: "Qualidade",
    content: "Invista em qualidade, não quantidade",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Trophy,
    title: "Conquistas",
    content: "Comemore metas alcançadas",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Zap,
    title: "Energia",
    content: "Reduza contas de energia com hábitos simples",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Flame,
    title: "Combustível",
    content: "Use apps para achar combustível barato",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
  },
  {
    icon: Moon,
    title: "Sono",
    content: "Durma bem para tomar decisões financeiras melhores",
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
  },
  {
    icon: Sun,
    title: "Otimismo",
    content: "Mantenha perspectiva positiva mas realista",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Cloud,
    title: "Nuvem",
    content: "Faça backup dos seus dados financeiros",
    color: "text-sky-400",
    bgColor: "bg-sky-500/10",
  },
  {
    icon: Droplet,
    title: "Água",
    content: "Economize água e reduza a conta",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: Flower,
    title: "Jardim",
    content: "Cultive hobbies que não custem caro",
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    icon: Trees,
    title: "Futuro",
    content: "Plante sementes financeiras hoje",
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  {
    icon: Home,
    title: "Moradia",
    content: "Mantenha custos de moradia abaixo de 30%",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Car,
    title: "Carro",
    content: "Considere custo total de propriedade",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: Bike,
    title: "Transporte",
    content: "Bicicleta pode economizar muito",
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  {
    icon: Bus,
    title: "Transporte Público",
    content: "Use quando possível para economizar",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Plane,
    title: "Viagens",
    content: "Planeje viagens com antecedência",
    color: "text-sky-400",
    bgColor: "bg-sky-500/10",
  },
  {
    icon: Train,
    title: "Mobilidade",
    content: "Compare meios de transporte",
    color: "text-slate-400",
    bgColor: "bg-slate-500/10",
  },
  {
    icon: Ship,
    title: "Importação",
    content: "Cuidado com taxas de importação",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Coffee,
    title: "Café",
    content: "Fazer em casa economiza muito no mês",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Beer,
    title: "Lazer",
    content: "Equilibre diversão e economia",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Pizza,
    title: "Alimentação",
    content: "Cozinhar em casa é mais saudável e barato",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
  },
  {
    icon: Apple,
    title: "Saúde",
    content: "Alimentação saudável previne gastos médicos",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: Cake,
    title: "Comemorações",
    content: "Celebre de forma simples e significativa",
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    icon: IceCream,
    title: "Pequenos Prazeres",
    content: "Permita-se com moderação",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: Camera,
    title: "Fotografia",
    content: "Use o celular antes de comprar câmera",
    color: "text-slate-400",
    bgColor: "bg-slate-500/10",
  },
  {
    icon: Music,
    title: "Entretenimento",
    content: "Assinaturas: avalie se usa mesmo",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    icon: Film,
    title: "Cinema",
    content: "Espere sair do streaming",
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    icon: Gamepad,
    title: "Games",
    content: "Espere promoções para comprar jogos",
    color: "text-violet-400",
    bgColor: "bg-violet-500/10",
  },
  {
    icon: Book,
    title: "Leitura",
    content: "Bibliotecas são gratuitas",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Pen,
    title: "Escrita",
    content: "Anote objetivos financeiros",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Briefcase,
    title: "Trabalho",
    content: "Negocie salário periodicamente",
    color: "text-slate-400",
    bgColor: "bg-slate-500/10",
  },
  {
    icon: Medal,
    title: "Reconhecimento",
    content: "Valorize suas conquistas",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Award,
    title: "Excelência",
    content: "Busque melhorar constantemente",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
  },
];
